######################################################################
##
## Filename: tb_Ctrl.udo
## Created on: Tue May 28 10:16:56 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
