######################################################################
##
## Filename: tb_Tx.udo
## Created on: Mon May 27 16:32:01 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
